import type { Track } from "./types";

export const tracks: Track[] = [
  {
    id: "kesariya-balam",
    title: "Kesariya Balam Padharo Mhare Desh",
    artist: "by Seema Mishra",
    category: "Rajasthani Folk",
    year: "2002",
    duration: "7:52",
    videoId: "_tDOaWIFfYI",
    spotifyUrl: "https://open.spotify.com/track/2HeOEpNnWIsikoFPtkY9po",
  },
  {
    id: "mishri-ko-baag-laga-de-rasiya",
    title: "Mishri Ko Baag Laga De Rasiya",
    artist: "by Seema Mishra",
    category: "Folk Dance",
    year: "2002",
    duration: "6:51",
    videoId: "PMWCFuGLHkA",
    spotifyUrl: "https://open.spotify.com/track/5hoSlKgzmo2L7oeMZXxedm",
  },
  {
    id: "jalalo-bilalo",
    title: "JALALO BILALO-A (Longing Of A Woman In Love)",
    artist: "by RAAHEIN Gharana x Shefali Khanna",
    category: "Rajasthani Folk",
    year: "2023",
    duration: "5:28",
    videoId: "jRr-RVqP-l0",
    spotifyUrl: "https://open.spotify.com/track/4ihRIDhpvXI8J5f9Csc6A6",
  },
  {
    id: "sundar-gori",
    title: "Sundar Gori",
    artist: "by SAZ",
    category: "Festive Folk",
    year: "2025",
    duration: "6:56",
    videoId: "araonQrXfpg",
    spotifyUrl: "https://open.spotify.com/track/1JjwBwLOd02jRIoa4wrsYs",
  },
  {
    id: "naina-ro-lobhi",
    title: "Naina Ro Lobhi",
    artist: "by Seema Mishra",
    category: "World Record Folk Dance",
    year: "2000",
    duration: "7:28",
    videoId: "obJpe-T-nA4",
    spotifyUrl: "https://open.spotify.com/track/2dVUPUGaJpoMOUKIHzWfC3",
  },
  {
    id: "boli-pyari-lage",
    title: "Boli Pyari Lage",
    artist: "by Kheta Khan & Kailash Jangid",
    category: "Rajasthani Folk",
    year: "2025",
    duration: "5:02",
    videoId: "4TSxPTfsF6U",
    spotifyUrl: "https://open.spotify.com/track/0Q4g4OIYjbmhSGe1UayiHY",
  },
  {
    id: "moomal",
    title: "Moomal",
    artist: "by Dapu Khan & Vibha Saraf",
    category: "Desert Ballad",
    year: "2018",
    duration: "4:52",
    videoId: "Ah1gS3ZtNrg",
    spotifyUrl: "https://open.spotify.com/track/34LzbD5SLqVtnXyvooIruY",
  },
  {
    id: "savariya-parnaye",
    title: "Savariya Parnaye",
    artist: "Divana",
    category: "Folk",
    year: "1996",
    duration: "7:44",
    videoId: "-OEh1EQ-vuM",
    spotifyUrl: "https://open.spotify.com/track/2Lbc28ETd6b7iGnBetgfCc",
  },
  {
    id: "hiwde-ro-haar",
    title: "Hiwde Ro Haar",
    artist: "by Akram Khan and Group",
    category: "Traditional Rajasthani Folk",
    year: "2001",
    duration: "4:25",
    videoId: "zOxgU11gw8g",
    spotifyUrl: "https://open.spotify.com/track/6duOTA2tv96iyo46JCZg5h",
  },
  {
    id: "aave-re-hichki",
    title: "Aave Re Hichki",
    artist: "by Mharo Barmer",
    category: "Rajasthani Original Langa Song",
    year: "2020",
    duration: "9:25",
    videoId: "IwiG-aSfDLg",
    spotifyUrl: "https://open.spotify.com/track/0bivfthRrQRvmGufTF7kxn",
  },
  {
    id: "chaudhary",
    title: "Chaudhary",
    artist: "by Amit Trivedi feat Mame Khan",
    category: "Folk Dance",
    year: "2012",
    duration: "7:00",
    videoId: "1gukvtH_a3I",
    spotifyUrl: "https://open.spotify.com/track/6U28uT3sr2xZlTniZEWiHI",
  },
  {
    id: "jala-sain",
    title: "Jala Sain",
    artist: "by Seema Mishra",
    category: "Rajasthani Wedding Song",
    year: "2002",
    duration: "7:10",
    videoId: "Azfrg__lLZQ",
    spotifyUrl: "https://open.spotify.com/track/3inHisUv4GAB0z0KsQ0Cxh",
  },
  {
    id: "ghoomar",
    title: "Ghoomar",
    artist: "by Seema Mishra",
    category: "Folk Dance",
    year: "2000",
    duration: "6:43",
    videoId: "nHhRWgkkpMk",
    spotifyUrl: "https://open.spotify.com/track/43CTiv7yzWjHEXf9nj1tyb",
  },
  {
    id: "railgaadi",
    title: "Railgaadi",
    artist: "by Achint & The Khan Brothers",
    category: "Folk Band Song",
    year: "2018",
    duration: "3:39",
    videoId: "YQGDuo6Uufg",
    spotifyUrl: "https://open.spotify.com/track/0usYBbHAMyaUXQWt6MPgRb",
  },
  {
    id: "kurjan",
    title: "Kurjan",
    artist: "by Seema Mishra",
    category: "Slow peaceful",
    year: "2001",
    duration: "9:26",
    videoId: "GMwzFdg1UrU",
    spotifyUrl: "https://open.spotify.com/track/1foU2FA5rID7yf3iU7b31Z",
  },
  {
    id: "manado-le-gayo",
    title: "Manado Le Gayo",
    artist: "by SAZ",
    category: "Desert Ballad",
    year: "2025",
    duration: "5:09",
    videoId: "plNUQU-GV5s",
    spotifyUrl: "https://open.spotify.com/track/3Qq4Yw1ipf8OGSl4tTVAzG",
  },
  {
    id: "lagayi-dyo-hariya-baag",
    title: "Lagayi Dyo Hariya Baag",
    artist: "by Jalal Khan",
    category: "Folk Music",
    year: "2021",
    duration: "4:41",
    videoId: "gEOQK7bwrtM",
    spotifyUrl: "https://open.spotify.com/track/0btGa7wqmNuXVUnaRZsZx8",
  },
  {
    id: "gori-jovey-baat",
    title: "Gori Jovey Baat",
    artist: "by Champe Khan",
    category: "Desert Ballad",
    year: "2021",
    duration: "5:50",
    videoId: "p4wzTHo8gbw",
    spotifyUrl: "https://open.spotify.com/track/3zdrn5wFSsMlqlyq9nTLz1",
  },
  {
    id: "samdariyo",
    title: "Samdariyo",
    artist: "by Hajari Gul",
    category: "Desert Ballad",
    year: "Traditional",
    duration: "4:32",
    videoId: "2xsf6_3QqQM",
    spotifyUrl: "https://open.spotify.com/track/7oajIHHEoJUKMZ1gW29QJH",
  },
  {
    id: "jaipur-su-lajo-tara-ri-chunari",
    title: "Jaipur Su Lajo Tara Ri Chunari",
    artist: "by Saraswati Devi Dhandhada & Heeralal Dhandhada",
    category: "Rajasthani Romantic Dance Song",
    year: "2024",
    duration: "8:06",
    videoId: "XJeHKEaGVQY",
    spotifyUrl: "https://open.spotify.com/track/71RDPSkjXYSz3zHmzkFTIB",
  },
  {
    id: "mitho-laage",
    title: "Mitho Laage",
    artist: "by Dhruv Ghanekar & Mame Khan",
    category: "Folk Song",
    year: "2016",
    duration: "4:35",
    videoId: "wy2eULa2fx0",
    spotifyUrl: "https://open.spotify.com/track/4mjjr1EeynuE236oOWeEMK",
  },
  {
    id: "chirmi",
    title: "Chirmi",
    artist: "by Arpita Ashish",
    category: "Rajasthani Lokgeet",
    year: "2011",
    duration: "6:21",
    videoId: "665oYRPh8Os",
    spotifyUrl: "https://open.spotify.com/track/5VmRESES2OFeZvWkDHAuIx",
  },
  {
    id: "halleriya",
    title: "Halleriya",
    artist: "by Musafir",
    category: "Folk Song",
    year: "2014",
    duration: "6:44",
    videoId: "2REzWgghg5c",
    spotifyUrl: "https://open.spotify.com/track/1GVeYGGaOVR9iW1dWtQjXz",
  },
  {
    id: "banro",
    title: "Banro",
    artist: "by Langas And Manganiars",
    category: "Folk Song",
    year: "2006",
    duration: "7:35",
    videoId: "x1dQ1qLnVPc",
    spotifyUrl: "https://open.spotify.com/track/3nYFR7zzV7lKN1hO5mTa0p",
  },
  {
    id: "jal-jamna-ro-pani",
    title: "Jal Jamna Ro Pani",
    artist: "by Seema Mishra",
    category: "Rajasthani Folk",
    year: "2002",
    duration: "6:29",
    videoId: "HpfpHKHoWXk",
    spotifyUrl: "https://open.spotify.com/track/0HW3UnlmCzG5K5cIC4YawY",
  },
  {
    id: "panihari",
    title: "Panihari",
    artist: "by Arun Rao · Maina Rao · Sushila Devi · suyash",
    category: "Folk Song",
    year: "2025",
    duration: "4:30",
    videoId: "e8TX7j-tPF4",
    spotifyUrl: "https://open.spotify.com/track/5SR4MTY9ZOVqqmx3WyXVXw",
  },
  {
    id: "umrao",
    title: "Umrao",
    artist: "by Seema Mishra",
    category: "Folk Song",
    year: "2024",
    duration: "15:13",
    videoId: "0qnqxfwhv7g",
    spotifyUrl: "https://open.spotify.com/track/5MgAt4ybfjwfNw3pqxBG31",
  },
  {
    id: "chand-chadyo-gignar",
    title: "Chand Chadyo Gignar",
    artist: "by Anupriya Lakhawat",
    category: "Folk Song",
    year: "2018",
    duration: "5:23",
    videoId: "0fF-ONW31Mc",
    spotifyUrl: "https://open.spotify.com/track/5O3aipPpooh44oVtIre5MM",
  },
  {
    id: "lagayi-dyo-hariya-baag",
    title: "Lagayi Dyo Hariya Baag",
    artist: "by Jalal Khan",
    category: "Folk Song",
    year: "2021",
    duration: "4:41",
    videoId: "gEOQK7bwrtM",
    spotifyUrl: "https://open.spotify.com/track/0btGa7wqmNuXVUnaRZsZx8",
  },
  {
    id: "hariyala-banna",
    title: "HARIYALA BANNA",
    artist: "by Ravindra Upadhyay, Kamal Choudhary, kunaal Vermaa, Kamal Choudhary",
    category: "Traditional Folk",
    year: "2016",
    duration: "4:58",
    videoId: "bWmo_WtKstE",
    spotifyUrl: "https://open.spotify.com/track/5fcG4c48IYby78Qfs3VQyZ",
  },
  {
    id: "piya-aao-to",
    title: "Piya Aao To",
    artist: "by Seema Mishra",
    category: "Folk Song",
    year: "2013",
    duration: "6:50",
    videoId: "gJTacBVk3ro",
    spotifyUrl: "https://open.spotify.com/track/0FuoPqR0TN4zK6R86nWpd2",
  },
  {
    id: "laal-peeli-akhiyaan",
    title: "Laal Peeli Akhiyaan",
    artist: "by Honey Trooper, Anuj Chitlangia and Rapperiya Baalam",
    category: "Folk Song",
    year: "2018",
    duration: "4:42",
    videoId: "vZVcjsvT_KA",
    spotifyUrl: "https://open.spotify.com/track/6BWM50D8c9GYaKu3PJOJ86",
  },
  {
    id: "kajaliyo",
    title: "Kajaliyo",
    artist: "by Aakanksha Sharma & Kapil Jangir",
    category: "Hit Rajasthani Song",
    year: "2018",
    duration: "3:22",
    videoId: "vZVcjsvT_KA",
    spotifyUrl: "https://open.spotify.com/track/5rxWxJUlJXiI45NIHBsFMm",
  },
];

export const defaultTrackId = tracks[0].id;
