import type { Track } from "./types";

export const tracks: Track[] = [
  {
    id: "kesariya-balam",
    title: "Kesariya Balam Padharo Mhare Desh",
    artist: "by Seema Mishra",
    category: "Rajasthani Folk",
    year: "2002",
    duration: "7:52",
    videoId: "_tDOaWIFfYI",
    spotifyUrl: "https://open.spotify.com/track/2HeOEpNnWIsikoFPtkY9po",
  },
  {
    id: "mishri-ko-baag-laga-de-rasiya",
    title: "Mishri Ko Baag Laga De Rasiya",
    artist: "by Seema Mishra",
    category: "Folk Dance",
    year: "2002",
    duration: "6:51",
    videoId: "PMWCFuGLHkA",
    spotifyUrl: "https://open.spotify.com/track/5hoSlKgzmo2L7oeMZXxedm",
  },
  {
    id: "jalalo-bilalo",
    title: "JALALO BILALO-A (Longing Of A Woman In Love)",
    artist: "by RAAHEIN Gharana x Shefali Khanna",
    category: "Rajasthani Folk",
    year: "2023",
    duration: "5:28",
    videoId: "jRr-RVqP-l0",
    spotifyUrl: "https://open.spotify.com/track/4ihRIDhpvXI8J5f9Csc6A6",
  },
  {
    id: "sundar-gori",
    title: "Sundar Gori",
    artist: "by SAZ",
    category: "Festive Folk",
    year: "2025",
    duration: "6:56",
    videoId: "araonQrXfpg",
    spotifyUrl: "https://open.spotify.com/track/1JjwBwLOd02jRIoa4wrsYs",
  },
  {
    id: "naina-ro-lobhi",
    title: "Naina Ro Lobhi",
    artist: "by Seema Mishra",
    category: "World Record Folk Dance",
    year: "2000",
    duration: "7:28",
    videoId: "obJpe-T-nA4",
    spotifyUrl: "https://open.spotify.com/track/2dVUPUGaJpoMOUKIHzWfC3",
  },
  {
    id: "boli-pyari-lage",
    title: "Boli Pyari Lage",
    artist: "by Kheta Khan & Kailash Jangid",
    category: "Rajasthani Folk",
    year: "2025",
    duration: "5:02",
    videoId: "4TSxPTfsF6U",
    spotifyUrl: "https://open.spotify.com/track/0Q4g4OIYjbmhSGe1UayiHY",
  },
  {
    id: "moomal",
    title: "Moomal",
    artist: "by Dapu Khan & Vibha Saraf",
    category: "Desert Ballad",
    year: "Traditional",
    duration: "4:52",
    videoId: "Ah1gS3ZtNrg",
    spotifyUrl: "https://open.spotify.com/track/34LzbD5SLqVtnXyvooIruY",
  },
  {
    id: "savariya-parnaye",
    title: "Savariya Parnaye",
    artist: "Divana",
    category: "Folk",
    year: "1996",
    duration: "7:44",
    videoId: "-OEh1EQ-vuM",
    spotifyUrl: "https://open.spotify.com/track/2Lbc28ETd6b7iGnBetgfCc",
  },
  {
    id: "hiwde-ro-haar",
    title: "Hiwde Ro Haar",
    artist: "by Akram Khan and Group",
    category: "Traditional Rajasthani Folk",
    year: "2001",
    duration: "4:25",
    videoId: "zOxgU11gw8g",
    spotifyUrl: "https://open.spotify.com/track/6duOTA2tv96iyo46JCZg5h",
  },
  {
    id: "aave-re-hichki",
    title: "Aave Re Hichki",
    artist: "by Mharo Barmer",
    category: "Rajasthani Original Langa Song",
    year: "2020",
    duration: "9:25",
    videoId: "IwiG-aSfDLg",
    spotifyUrl: "https://open.spotify.com/track/0bivfthRrQRvmGufTF7kxn",
  },
];

export const defaultTrackId = tracks[0].id;
